#!/usr/bin/env python3
"""Regenerate web/sources.js from src/novel_workflow/*.py.

The web live runner mounts the real package sources into Pyodide's
in-browser filesystem so the browser execution path runs the same code
as the CLI and the MCP server. ``web/sources.js`` is that snapshot,
encoded as a JSON object assigned to ``window.NW_SOURCES`` — a verbatim
copy of every Python file in the package, no transforms, no minification.

Run this after any change to the Python package so the three surfaces
(CLI / MCP / web) stay on the same core contract:

    python scripts/gen_web_sources.py

The script is the single entry point for keeping the contract honest.
Editing ``web/sources.js`` by hand will be silently overwritten on the
next run; do not commit hand-edits.

Adding a new package file? Append it to ``FILES`` below. The file list is
intentionally explicit (not a glob) so the snapshot is deterministic and
auditable — the order is part of the contract.

Why every file, including mcp_server.py: cli.py imports mcp_server at
parser-build time (``from . import mcp_server``). The browser runner will
never invoke the MCP server (stdio has no meaning inside Pyodide), but
import resolution must still succeed, so the file is bundled.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "novel_workflow"
OUT = ROOT / "web" / "sources.js"

# Package files mounted into the browser-side Pyodide filesystem.
# Order matches the directory listing; do not reorder casually.
FILES = [
    "__init__.py",
    "_security.py",
    "_visual.py",
    "cli.py",
    "core.py",
    "library.py",
    "mcp_server.py",
    "model_adapter.py",
    "model_cli.py",
]


def main() -> int:
    missing = [name for name in FILES if not (SRC / name).is_file()]
    if missing:
        raise SystemExit(f"missing source files under {SRC}: {missing}")

    data = {name: (SRC / name).read_text(encoding="utf-8") for name in FILES}

    # ensure_ascii=False keeps CJK / non-ASCII source readable in the JS
    # payload and matches the historical format of web/sources.js. JSON
    # still escapes control characters, so the payload is safe to embed.
    payload = json.dumps(data, ensure_ascii=False, indent=None, separators=(",", ":"))

    header = (
        "// novel-agent-workflow package source, verbatim from src/novel_workflow/.\n"
        "// Generated by scripts/gen_web_sources.py — do not edit by hand.\n"
        "// Mounted read-only into the Pyodide in-browser filesystem at runtime.\n"
    )
    OUT.write_text(header + "window.NW_SOURCES = " + payload + ";\n", encoding="utf-8")

    total = sum(len(v) for v in data.values())
    print(f"wrote {OUT.relative_to(ROOT)} ({len(payload)} bytes, {len(data)} files, {total} source chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
